### PR TITLE
Documentation syntaxtree tutorial

### PR DESCRIPTION
**Pull request by pwochner**
Adding a tutorial on ASTs, how they are represented in Herb and how they can be modified.

### CODE REVIEW

**Comment by IssaHanou** [comment]
Looks nice! I think these are good examples.

Few minor typos:
- Line 18: represent as **an** abstract 
- Line 29: grammer &rarr; grammar
- Line 31: in the context of program synthesis **,**

it might be nice to also show the evaluation of the AST (using `eval`) if you store a value in `input1` then you can check if the rule node program is correct

**Comment by pwochner** [comment]
> Looks nice! I think these are good examples.
> 
> Few minor typos:
> 
>     * Line 18: represent as **an** abstract
> 
>     * Line 29: grammer → grammar
> 
>     * Line 31: in the context of program synthesis **,**
> 
> 
> it might be nice to also show the evaluation of the AST (using `eval`) if you store a value in `input1` then you can check if the rule node program is correct


> Looks nice! I think these are good examples.
> 
> Few minor typos:
> 
>     * Line 18: represent as **an** abstract
> 
>     * Line 29: grammer → grammar
> 
>     * Line 31: in the context of program synthesis **,**
> 
> 
> it might be nice to also show the evaluation of the AST (using `eval`) if you store a value in `input1` then you can check if the rule node program is correct

I added evaluating the ASTs on some input examples using `execute_on_input`.

**Comment by sebdumancic** [comment]
Could we change this
```
function fizzbuzz(x)
    if x % 5 == 0 && x % 3 == 0
        return Dict(:output1 => "FizzBuzz")
    else
        if x % 3 == 0
            return Dict(:output1 => "Fizz")
        else
            if x % 5 == 0
                return Dict(:output1 => "Buzz")
            else
                return Dict(:output1 => string(x))
            end
        end
    end
end
```

into 

```
function fizzbuzz(x)
    if x % 5 == 0 && x % 3 == 0
        return "FizzBuzz"
    else
        if x % 3 == 0
            return  "Fizz"
        else
            if x % 5 == 0
                return "Buzz"
            else
                return string(x)
            end
        end
    end
end
```
?

Simply because it looks nicer and less weird. Returning the dict is a convention we made if we would do synthesis, but otherwise is a bit weird.

**Comment by pwochner** [comment]
Updated `fizz_buzz()` and grammar to return String instead of Dict.

**Pull request merged**
